import { Product } from "@/types/common/types";

export const products: Product[] = [
  {
    id: 1,
    name: "Diamond Ring",
    description: "A beautiful diamond ring.",
    rating: 5,
    price: 500,
    discountedPrice: 450,
    tags: ["ring", "diamond"],
    image: "/assets/diamond_ring.jpg",
  },
  {
    id: 2,
    name: "Gold Necklace",
    description: "A stunning gold necklace.",
    rating: 4,
    price: 700,
    discountedPrice: 650,
    tags: ["necklace", "gold"],
    image: "/assets/gold_necklace.jpg",
  },
  {
    id: 3,
    name: "Sapphire Earrings",
    description: "Elegant sapphire earrings for a sophisticated look.",
    rating: 4.5,
    price: 800,
    discountedPrice: 750,
    tags: ["earrings", "sapphire"],
    image: "/assets/sapphire_earrings.jpg",
  },
  {
    id: 4,
    name: "Rose Gold Bracelet",
    description: "Chic rose gold bracelet to complement any outfit.",
    rating: 4.2,
    price: 350,
    discountedPrice: 320,
    tags: ["bracelet", "rose gold"],
    image: "/assets/rose_gold_bracelet.jpg",
  },
  {
    id: 5,
    name: "Emerald Pendant",
    description: "Exquisite emerald pendant for a touch of luxury.",
    rating: 4.8,
    price: 600,
    discountedPrice: 550,
    tags: ["pendant", "emerald"],
    image: "/assets/emerald_pendant.jpg",
  },
  {
    id: 6,
    name: "Silver Hoop Earrings",
    description: "Classic silver hoop earrings for everyday elegance.",
    rating: 4.3,
    price: 150,
    discountedPrice: 130,
    tags: ["earrings", "silver"],
    image: "/assets/silver_hoop_earrings.jpg",
  },
  {
    id: 7,
    name: "Ruby Ring",
    description: "Striking ruby ring for a bold and vibrant look.",
    rating: 4.7,
    price: 550,
    discountedPrice: 500,
    tags: ["ring", "ruby"],
    image: "/assets/ruby_ring.jpg",
  },
  {
    id: 8,
    name: "Pearl Drop Earrings",
    description: "Timeless pearl drop earrings for a classic touch.",
    rating: 4.6,
    price: 200,
    discountedPrice: 180,
    tags: ["earrings", "pearl"],
    image: "/assets/pearl_drop_earrings.jpg",
  },
  {
    id: 9,
    name: "Platinum Wedding Band",
    description: "Elegant platinum wedding band for a lifelong commitment.",
    rating: 4.9,
    price: 1000,
    discountedPrice: 950,
    tags: ["wedding band", "platinum"],
    image: "/assets/platinum_wedding_band.jpg",
  },
  {
    id: 10,
    name: "Opal Brooch",
    description: "Unique opal brooch to add a pop of color to any ensemble.",
    rating: 4.4,
    price: 300,
    discountedPrice: 280,
    tags: ["brooch", "opal"],
    image: "/assets/opal_brooch.jpg",
  },
  {
    id: 11,
    name: "Tanzanite Necklace",
    description: "Dazzling tanzanite necklace for a touch of glamour.",
    rating: 4.5,
    price: 900,
    discountedPrice: 850,
    tags: ["necklace", "tanzanite"],
    image: "/assets/tanzanite_necklace.jpg",
  },
  {
    id: 12,
    name: "Citrine Bracelet",
    description: "Radiant citrine bracelet to brighten up your look.",
    rating: 4.1,
    price: 250,
    discountedPrice: 220,
    tags: ["bracelet", "citrine"],
    image: "/assets/citrine_bracelet.jpg",
  },
  // Add more products here if needed
];
